development:
  adapter: postgresql
  encoding: unicode
  database: magazine_development
  host: localhost
  pool: 5
  username: username
  password: password


test:
  adapter: postgresql
  encoding: unicode
  database: magazine_development
  host: localhost
  pool: 5
  username: username
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: magazine_development
  host: localhost
  pool: 5
  username: username
  password: password
  