
default: &default
  adapter: mysql2
  username: root
  password: root
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: magazine_development

production:
 development:
  adapter: mysql2
  encoding: utf8
  database: magazine_production
  pool: 5
  username: root
  password: root
